name: Build images and add to ghcr.io upon release
on:
  release:
    types:
      - published

jobs:
  operator_image:
    name: Push operator image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: stolon-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/mannemsolutions/stolon,enable=true
          tags: |
            type=semver,pattern={{raw}}
            type=raw,value=latest
            type=sha

      - name: Build and push stolon images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ${{ steps.stolon-meta.outputs.tags }}
          labels: ${{ steps.stolon-meta.outputs.labels }}
          build-args: VERSION=${{ github.ref_name }}
